"""Refresh the PostgreSQL review warehouse from the Gold CSV tables."""
import os
from pathlib import Path

import pandas as pd
import psycopg

SCHEMA = """
CREATE TABLE IF NOT EXISTS dim_category (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS dim_price_band (
    price_band_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_band_name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS dim_rating (
    rating INTEGER PRIMARY KEY CHECK (rating BETWEEN 1 AND 5)
);
CREATE TABLE IF NOT EXISTS dim_sentiment (
    sentiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sentiment_name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS dim_product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL UNIQUE,
    category_id BIGINT NOT NULL REFERENCES dim_category(category_id)
);
CREATE TABLE IF NOT EXISTS fact_review_aggregate (
    category_id BIGINT NOT NULL REFERENCES dim_category(category_id),
    price_band_id BIGINT NOT NULL REFERENCES dim_price_band(price_band_id),
    rating INTEGER NOT NULL REFERENCES dim_rating(rating),
    sentiment_id BIGINT NOT NULL REFERENCES dim_sentiment(sentiment_id),
    review_count BIGINT NOT NULL,
    sum_price NUMERIC(18, 2) NOT NULL,
    sum_words BIGINT NOT NULL,
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (category_id, price_band_id, rating, sentiment_id)
);
CREATE TABLE IF NOT EXISTS fact_product_summary (
    product_id BIGINT PRIMARY KEY REFERENCES dim_product(product_id),
    review_count BIGINT NOT NULL,
    average_rating NUMERIC(4, 2) NOT NULL,
    positive_percent NUMERIC(5, 2) NOT NULL,
    negative_percent NUMERIC(5, 2) NOT NULL,
    average_price NUMERIC(12, 2) NOT NULL,
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

def dimension_id(connection, table, id_column, name_column, value):
    row = connection.execute(
        f"INSERT INTO {table} ({name_column}) VALUES (%s) "
        f"ON CONFLICT ({name_column}) DO UPDATE SET {name_column} = EXCLUDED.{name_column} "
        f"RETURNING {id_column}",
        (value,),
    ).fetchone()
    return row[0]

def load_gold(gold_dir, database_url):
    gold_dir = Path(gold_dir)
    cube_path = gold_dir / "cube.csv"
    products_path = gold_dir / "products.csv"
    if not cube_path.exists() or not products_path.exists():
        raise FileNotFoundError(f"Expected {cube_path} and {products_path}")

    cube = pd.read_csv(cube_path)
    products = pd.read_csv(products_path)

    with psycopg.connect(database_url) as connection:
        connection.execute(SCHEMA)
        for rating in sorted(cube["rating"].dropna().astype(int).unique()):
            connection.execute(
                "INSERT INTO dim_rating (rating) VALUES (%s) ON CONFLICT DO NOTHING",
                (rating,),
            )

        connection.execute("TRUNCATE fact_review_aggregate, fact_product_summary")
        for row in cube.itertuples(index=False):
            category_id = dimension_id(
                connection, "dim_category", "category_id", "category_name", row.category
            )
            price_band_id = dimension_id(
                connection, "dim_price_band", "price_band_id", "price_band_name",
                row.price_band,
            )
            sentiment_id = dimension_id(
                connection, "dim_sentiment", "sentiment_id", "sentiment_name", row.sentiment
            )
            connection.execute(
                """INSERT INTO fact_review_aggregate
                   (category_id, price_band_id, rating, sentiment_id,
                    review_count, sum_price, sum_words)
                   VALUES (%s, %s, %s, %s, %s, %s, %s)""",
                (category_id, price_band_id, int(row.rating), sentiment_id,
                 int(row.reviews), float(row.sum_price), int(row.sum_words)),
            )

        for row in products.itertuples(index=False):
            category_id = dimension_id(
                connection, "dim_category", "category_id", "category_name", row.category
            )
            product_id = connection.execute(
                """INSERT INTO dim_product (product_name, category_id) VALUES (%s, %s)
                   ON CONFLICT (product_name) DO UPDATE SET category_id = EXCLUDED.category_id
                   RETURNING product_id""",
                (row.product_name, category_id),
            ).fetchone()[0]
            connection.execute(
                """INSERT INTO fact_product_summary
                   (product_id, review_count, average_rating, positive_percent,
                    negative_percent, average_price)
                   VALUES (%s, %s, %s, %s, %s, %s)""",
                (product_id, int(row.reviews), float(row.avg_rating),
                 float(row.pct_positive), float(row.pct_negative), float(row.avg_price)),
            )

        fact_count = connection.execute(
            "SELECT COUNT(*) FROM fact_review_aggregate"
        ).fetchone()[0]
        product_count = connection.execute(
            "SELECT COUNT(*) FROM fact_product_summary"
        ).fetchone()[0]

    print(f"Loaded {fact_count:,} review aggregates and {product_count:,} product summaries.")


if __name__ == "__main__":
    load_gold(
        os.getenv("GOLD_DIR", "data/gold"),
        os.getenv(
            "DATABASE_URL",
            "postgresql://bda_user:bda_local_password@localhost:5432/review_warehouse",
        ),
    )