FROM apache/airflow:2.10.5-python3.11

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements-pipeline.txt /tmp/requirements-pipeline.txt
RUN pip install --no-cache-dir "psycopg2-binary" "psycopg[binary]" \
    && pip install --no-cache-dir -r /tmp/requirements-pipeline.txt

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64